### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by nighthawks-hopper** [loukkis/win-2nd-teams-instance-launcher#1]
![image](https://user-images.githubusercontent.com/72955903/117736413-7b334a80-b232-11eb-8962-900d570d5d30.png)

I recently have an error above.
I can't start the second instance.

**Comment by jschwartzenberg** [comment]
Same here, it seems either a directory needs to be created in the `USERPROFILE` structure used by the second instance or maybe a symlink to the real downloads directory.

**Comment by jschwartzenberg** [comment]
I found a solution here:
https://danielsmon.com/2020/04/02/multiple-ms-teams-accounts-on-the-desktop/

Next the the `AppData` directory there should be a `Downloads` directory. With this tool, create:
`%LOCALAPPDATA%\Microsoft\Teams\Downloads`

**Comment by loukkis** [comment]
Thanks. I'll update the code and binaries tonight. Stay tuned.

**Comment by nighthawks-hopper** [comment]
I made the directory:
%LOCALAPPDATA%\Microsoft\Teams\Downloads
I could launch the second instance.
Thank you.

**Comment by loukkis** [comment]
New version 0.5 available, which creates Download folder on first run if not exist.
